# Generated by Django 3.1.4 on 2020-12-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(default='SEM IMAGEM', upload_to='media'),
        ),
    ]
